version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "DisableAccessKeyDaily"
s3_bucket = "sam-bucket-application"
s3_prefix = "DisableAccessKeyDaily"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Environment=\"Production\""

